# -*- coding: utf-8 -*-
"""cnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189RvVX6p_lv_BrzNYy1CvbLkfBngzL3h
"""

import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import joblib
from keras.callbacks import TensorBoard
import time

# Carregar o arquivo CSV
# Caminho do dataset
dataset_dir = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQHXeGnay1fBg89k_lUubL_3WsML0F7lrjDTF96jMUGaFDXGjR9Y_ca7g8cjjG4XzHSZoJo7bFp1ZWF/pub?gid=1447023203&single=true&output=csv'
df = pd.read_csv(dataset_dir)

# Dividir os dados em conjuntos de treinamento e teste
X = df['preprocessed_news']  # texto das notícias pré-processadas
y = df['label']  # rótulos (fake ou true)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Converter os rótulos para valores numéricos
y_train = np.array([0 if label == 'fake' else 1 for label in y_train])
y_test = np.array([0 if label == 'fake' else 1 for label in y_test])

# Tokenização e vetorização
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)
X_train_sequence = tokenizer.texts_to_sequences(X_train)
X_test_sequence = tokenizer.texts_to_sequences(X_test)

vocab_size = len(tokenizer.word_index) + 1
max_length = max([len(s.split()) for s in X_train])

X_train_padded = pad_sequences(X_train_sequence, maxlen=max_length, padding='post')
X_test_padded = pad_sequences(X_test_sequence, maxlen=max_length, padding='post')

# Construção da CNN com Leaky ReLU
model = Sequential()
model.add(Embedding(vocab_size, 100, input_length=max_length))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='SGD', loss='binary_crossentropy', metrics=['accuracy'])

# Criar um callback para o TensorBoard
tensorboard_callback = TensorBoard(log_dir="logs/{}".format(time.time()))

# Treinamento do modelo
model.fit(X_train_padded, y_train, epochs=10, batch_size=64, validation_split=0.2, callbacks=[tensorboard_callback])

# Avaliação do modelo
loss, accuracy = model.evaluate(X_test_padded, y_test)
print("Test Accuracy:", accuracy)

# Salvar o modelo no formato nativo do Keras
model.save('modelo_cnn.keras')

print("Modelo salvo localmente.")

# Salvar o tokenizador usando joblib
joblib.dump(tokenizer, 'tokenizer.joblib')

print("Tokenizador salvo localmente.")